---
spring:
  profiles: test
variables:
  name: test-YAML
  environment: testing
  enabled: false
  servers: www.abc.test.com, www.xyz.test.com
  hops:
    -
      id: 1
      role: aa
    -
      id: 2
      role: 55
  baseURL: https://jsonplaceholder.typicode.com





